### PR TITLE
Adapting project to new dapp tool + update ds-auth dependency

### PR DESCRIPTION
**Pull request by gbalabasquer**
@nmushegian please check when you can

### CODE REVIEW

**Comment by gbalabasquer** [comment]
@apmilen could you take a look to this, please?

**Comment by nmushegian** [comment]
lgtm

**Comment by gbalabasquer** [comment]
@nmushegian thanks, will merge it.

**Comment by gbalabasquer** [comment]
@nmushegian ah no, can not do it in this repo. Some of you should do it. Thanks.

**Pull request merged**
